language: java
sudo: true
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: build vaunt with gradle & generate reports
    script:
    - ./gradlew clean build jacocoRootReport coveralls
  - stage: release to maven central
    deploy:
      skip_cleanup: true
      provider: script
      on:
        branch: master
        tags: true
      script: bash deploy-to-maven-central.sh
