language: java
sudo: true

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: build vaunt-generator with gradle & generate reports
    script:
    - cd vaunt-generator
    - ./gradlew clean build jacocoTestReport coveralls
  - stage: build vaunt-validator with gradle & generate reports
    script:
      - cd vaunt-validator
      - ./gradlew clean build jacocoTestReport coveralls
